export const CATEGORIES_COLLECTIONS = [
    {
        id: 1,
        value: 'art',
        label: 'Art',
        icon: 'fa-image',
        title: 'Explore Art',
        description: 'Explore NFT art and collectible projects as well as utility tokens for virtual land and other unique Web3 experiences.',
        banner: '../img/categories/art.jpg',
        bg: 'img/categories/art.jpg',
    },
    {
        id: 2,
        value: 'boats',
        label: 'Boats',
        icon: 'fa-ship',
        title: 'Explore Boats',
        description: 'Register and connect your floating kingdom to a virtual representation of it on the blockchain.',
        banner: '../img/categories/boats.jpg',
        bg: 'img/categories/boats.jpg',
    },
    {
        id: 3,
        value: 'cars',
        label: 'Cars',
        icon: 'fa-car',
        title: 'Explore Cars',
        description: 'Link your car to a unique NFT and unlock manufacturer benefits, car history, warranty information, and other specifial benefits ',
        banner: '../img/categories/cars.jpg',
        bg: 'img/categories/cars.jpg',    
    },
    {
        id: 4,
        value: 'fashion',
        label: 'Fashion',
        icon: 'fa-shopping-bag',
        title: 'Explore Fashion',
        description: 'NFT your fashion and bling out your avatar with the latest trends on social media. Get invited to special access events and promotions',
        banner: '../img/categories/fashion.jpg',
        bg: 'img/categories/fashion.jpg',   
    },
    {
        id: 5,
        value: 'jewelry',
        label: 'Jewelry',
        icon: 'fa-diamond',
        title: 'Explore Jewelry',
        description: 'Store certifications and appraisals of your precious, one-of-a-kind valuables in an NFT for all time on the blockchain.',
        banner: '../img/categories/jewelry.jpg',
        bg: 'img/categories/jewelry.jpg',   
    },
    {
        id: 6,
        value: 'planes',
        label: 'Planes',
        icon: 'fa-plane',
        title: 'Explore Planes',
        description: 'Register your flying palace on the blockchain using NFTs and explore the benefits.',
        banner: '../img/categories/planes.jpg',
        bg: 'img/categories/planes.jpg',   
    },
    {
        id: 7,
        value: 'realEstate',
        label: 'Real Estate',
        icon: 'fa-home',
        title: 'Explore Real Estate',
        description: 'Record your house using an NFT on the blockchain.',
        banner: '../img/categories/homes.jpg',
        bg: 'img/categories/homes.jpg',   
    },
    {
        id: 8,
        value: 'watches',
        label: 'Watches',
        icon: 'fa-th',
        title: 'Explore Watches',
        description: 'Get invited to special access events and promotions. Save warranty and repair information in an NFT.',
        banner: '../img/categories/watches.jpg',
        bg: 'img/categories/watches.jpg',   
    },
    {
        id: 9,
        value: 'wine',
        label: 'Wine',
        icon: 'fa-glass',
        title: 'Explore Wine',
        description: 'Collect unique, collectibles of your favorite wine or drink in an NFT.',
        banner: '../img/categories/drinks.jpg',
        bg: 'img/categories/drinks.jpg',   
    },
    {
        id: 10,
        value: 'event',
        label: 'Event',
        icon: 'fa-file-movie-o',
        title: 'Explore Event',
        description: 'Pay, receive, and store your ticket to an event on the blockchain.',
        banner: '../img/categories/events.png',
        bg: 'img/categories/events.png',   
    },
    {
        id: 11,
        value: 'certifications',
        label: 'Certifications',
        icon: 'fa fa-trophy',
        title: 'Explore Certifications',
        description: 'Store your diploma, certification, license, or other important information that needs to be visible for others on a tamper-proof NFT.',
        banner: '../img/categories/certificate.png',
        bg: 'img/categories/certificate.png',   
    },
    {
        id: 12,
        value: 'electronics',
        label: 'Electronics',
        icon: 'fa fa-plug',
        title: 'Explore Electronics',
        description: 'Store your diploma, certification, license, or other important information that needs to be visible for others on a tamper-proof NFT.',
        banner: '../img/categories/electronics.jpg',
        bg: 'img/categories/electronics.jpg',   
    }
  ];