export const GET_NFT721_DATA = 'GET_NFT721_DATA';
export const GET_LAZY_COLLECTION_DATA = 'GET_LAZY_COLLECTION_DATA';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_MAGIC_DATA = 'GET_MAGIC_DATA';
export const LOG_OUT_MAGIC_DATA = 'LOG_OUT_MAGIC_DATA';

export const UPDATE_CREATOR_NFT = 'UPDATE_CREATOR_NFT';
export const EMPTY_CREATOR_NFT = 'EMPTY_CREATOR_NFT';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const EMPTY_SEARCH = 'EMPTY_SEARCH';

export const UPDATE_GATED_NFT = 'UPDATE_GATED_NFT';
export const EMPTY_GATED_NFT = 'EMPTY_GATED_NFT';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const BADGE_COUNT = 'BADGE_COUNT';

export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';

export const UPDATE_SETTING_LEFT_SIDEBAR = 'UPDATE_SETTING_LEFT_SIDEBAR';
export const UPDATE_SETTING_RIGHT_SIDEBAR = 'UPDATE_SETTING_RIGHT_SIDEBAR';